/**
 * Specific mock AI notes for organized folder structure
 */

export function getSpecificFolderNote(folderPath: string, folderName: string): string | null {
  const folderNameLower = folderName.toLowerCase()
  const now = new Date()
  
  // Archives folder
  if (folderNameLower === 'archives' || folderNameLower.includes('archive')) {
    return [
      '# 📦 Archives',
      '',
      `**Path:** ${folderPath}`,
      '**Purpose:** Long-term storage and backup',
      `**Last Updated:** ${now.toLocaleDateString()}`,
      '',
      '## Overview',
      '',
      'This folder serves as your central archive for older files, completed projects, and documents that are no longer actively used but need to be retained for reference or compliance purposes.',
      '',
      '## Organization Strategy',
      '',
      '- **Chronological sorting** - Files organized by year/quarter',
      '- **Category-based folders** - Grouped by project or department',
      '- **Compression ready** - Consider zipping older content to save space',
      '',
      '## AI Recommendations',
      '',
      '- ✅ Well-organized for long-term storage',
      '- 💡 Consider moving files older than 2 years to compressed archives',
      '- 🔍 Add README files to explain archived project context',
      '- 📊 Current storage: Moderate usage',
      '',
      '## Best Practices',
      '',
      '1. **Regular reviews**: Check quarterly for files that can be permanently deleted',
      '2. **Metadata**: Include dates and descriptions in file names',
      '3. **Backup**: Ensure archived content is backed up externally',
      '',
      '---',
      `*AI-generated insights • ${now.toLocaleTimeString()}*`,
    ].join('\n')
  }
  
  // Images folder
  if (folderNameLower === 'image' || folderNameLower === 'images' || folderNameLower.includes('image')) {
    return [
      '# 🖼️ Images',
      '',
      `**Path:** ${folderPath}`,
      '**Purpose:** Visual content and media storage',
      `**Last Updated:** ${now.toLocaleDateString()}`,
      '',
      '## Overview',
      '',
      'Your central repository for image files, photos, graphics, and visual assets. This folder contains various image formats organized for easy access and management.',
      '',
      '## File Types Detected',
      '',
      '- **Photos**: JPG, PNG, HEIC',
      '- **Graphics**: SVG, AI, PSD',
      '- **Screenshots**: PNG, JPG',
      '- **Thumbnails**: Cached preview files',
      '',
      '## AI Insights',
      '',
      '- 📸 **Organization Level:** Images are ready for categorization',
      '- 💾 **Storage Optimization:** Consider converting large PNGs to JPG',
      '- 🏷️ **Tagging:** Add metadata tags for easier searching',
      '- 📊 **Duplicate Detection:** Check for similar images',
      '',
      '## Recommended Actions',
      '',
      '1. Create subfolders for different categories',
      '2. Use descriptive file names with dates (YYYY-MM-DD format)',
      '3. Remove duplicate or low-quality images',
      '4. Consider cloud backup for precious memories',
      '',
      '---',
      `*AI-generated insights • ${now.toLocaleTimeString()}*`,
    ].join('\n')
  }
  
  // Music folder
  if (folderNameLower === 'music' || folderNameLower.includes('music') || folderNameLower.includes('audio')) {
    return [
      '# 🎵 Music',
      '',
      `**Path:** ${folderPath}`,
      '**Purpose:** Audio files and music library',
      `**Last Updated:** ${now.toLocaleDateString()}`,
      '',
      '## Overview',
      '',
      'Your music library containing audio files, playlists, and sound recordings. This folder is optimized for media player organization and playback.',
      '',
      '## Audio Formats',
      '',
      '- **Lossless**: FLAC, WAV, ALAC',
      '- **Compressed**: MP3, AAC, OGG',
      '- **Playlists**: M3U, PLS',
      '- **Metadata**: ID3 tags, album art',
      '',
      '## AI Organization Tips',
      '',
      '- 🎼 **Folder Structure:** Artist → Album → Tracks',
      '- 🏷️ **Metadata Quality:** Ensure proper ID3 tags for all files',
      '- 📻 **Playlist Management:** Create themed playlists in subfolders',
      '- 💿 **Quality Check:** Consider upgrading low-bitrate files',
      '',
      '## Recommendations',
      '',
      '1. Organize by Artist/Album/Track Number format',
      '2. Add album artwork to all music folders',
      '3. Create smart playlists for different moods/activities',
      '4. Remove duplicates and incomplete downloads',
      '5. Backup your music library regularly',
      '',
      '## Media Player Integration',
      '',
      'Compatible with iTunes, Windows Media Player, VLC, and most music streaming apps.',
      '',
      '---',
      `*AI-generated insights • ${now.toLocaleTimeString()}*`,
    ].join('\n')
  }
  
  // Application folder
  if (folderNameLower === 'application' || folderNameLower === 'applications' || folderNameLower.includes('app')) {
    return [
      '# 💻 Applications',
      '',
      `**Path:** ${folderPath}`,
      '**Purpose:** Installed programs and software packages',
      `**Last Updated:** ${now.toLocaleDateString()}`,
      '',
      '## Overview',
      '',
      'This folder contains application installers, portable apps, and software packages. It serves as your software library for installations and updates.',
      '',
      '## Content Types',
      '',
      '- **Installers**: EXE, MSI, DMG, PKG',
      '- **Portable Apps**: Standalone executables',
      '- **Updates**: Patch files and updaters',
      '- **Licenses**: Software keys and activation files',
      '',
      '## AI Security Insights',
      '',
      '- 🔒 **Security Check:** Scan all installers before running',
      '- 🔄 **Update Status:** Check for latest versions regularly',
      '- 📝 **License Management:** Keep activation keys secure',
      '- 🗑️ **Cleanup:** Remove old installers after successful installation',
      '',
      '## Organization Strategy',
      '',
      '1. **By Category**: Productivity, Development, Media, Utilities',
      '2. **Version Control**: Include version numbers in file names',
      '3. **README Files**: Add notes about installation requirements',
      '4. **Source Tracking**: Note where each app was downloaded from',
      '',
      '## Best Practices',
      '',
      '- ✅ Keep only current versions',
      '- ✅ Verify checksums/signatures before installing',
      '- ✅ Maintain separate folder for portable apps',
      '- ✅ Document custom configurations',
      '',
      '---',
      `*AI-generated insights • ${now.toLocaleTimeString()}*`,
    ].join('\n')
  }
  
  // Video folder
  if (folderNameLower === 'video' || folderNameLower === 'videos' || folderNameLower.includes('video')) {
    return [
      '# 🎬 Videos',
      '',
      `**Path:** ${folderPath}`,
      '**Purpose:** Video files and multimedia content',
      `**Last Updated:** ${now.toLocaleDateString()}`,
      '',
      '## Overview',
      '',
      'Your video library containing movies, recordings, tutorials, and multimedia content. This folder manages various video formats and resolutions.',
      '',
      '## Video Formats Supported',
      '',
      '- **High Quality**: MP4, MKV, MOV, AVI',
      '- **Streaming**: WEBM, FLV',
      '- **Projects**: Premiere, Final Cut, DaVinci files',
      '- **Subtitles**: SRT, VTT files',
      '',
      '## AI Insights',
      '',
      '- 🎥 **Content Type:** Mix of personal recordings and downloaded content',
      '- 💾 **Storage Impact:** Videos consume significant disk space',
      '- 🎞️ **Quality Optimization:** Consider converting to H.265 for better compression',
      '- 📱 **Device Compatibility:** Ensure formats work across all your devices',
      '',
      '## Organization Recommendations',
      '',
      '1. **Categories**: Movies, TV Shows, Personal, Tutorials, Projects',
      '2. **Naming Convention**: Title (Year) [Quality]',
      '3. **Metadata**: Include resolution and codec info',
      '4. **Subtitles**: Keep subtitle files with same name as video',
      '',
      '## Storage Optimization',
      '',
      '- 🔄 Convert large files to H.265/HEVC codec',
      '- 🗜️ Use appropriate bitrates for content type',
      '- 📊 Archive old content to external drives',
      '- 🎯 Remove duplicate or low-quality versions',
      '',
      '## Playback Compatibility',
      '',
      'Compatible with VLC, Windows Media Player, QuickTime, and most media centers.',
      '',
      '---',
      `*AI-generated insights • ${now.toLocaleTimeString()}*`,
    ].join('\n')
  }
  
  // Documents folder
  if (folderNameLower === 'documents' || folderNameLower.includes('document') || folderNameLower.includes('docs')) {
    return [
      '# 📄 Documents',
      '',
      `**Path:** ${folderPath}`,
      '**Purpose:** Text documents, spreadsheets, and office files',
      `**Last Updated:** ${now.toLocaleDateString()}`,
      '',
      '## Overview',
      '',
      'Your primary workspace for document management, containing text files, spreadsheets, presentations, and PDFs. This is your digital filing cabinet for important documents.',
      '',
      '## Document Types',
      '',
      '- **Text**: DOCX, TXT, RTF, ODT',
      '- **Spreadsheets**: XLSX, CSV, ODS',
      '- **Presentations**: PPTX, KEY, ODP',
      '- **PDFs**: Portable documents and forms',
      '- **Notes**: MD, Markdown, OneNote',
      '',
      '## AI Organization Analysis',
      '',
      '- 📊 **Organization Level:** Moderately organized with room for improvement',
      '- 🔍 **Searchability:** Add meaningful file names and tags',
      '- 📁 **Folder Structure:** Consider subcategories (Work, Personal, Finance, etc.)',
      '- 🔄 **Version Control:** Implement naming convention for versions',
      '',
      '## Recommended Structure',
      '',
      '```',
      'Documents/',
      '├── Work/',
      '│   ├── Reports/',
      '│   ├── Presentations/',
      '│   └── Correspondence/',
      '├── Personal/',
      '│   ├── Finance/',
      '│   ├── Medical/',
      '│   └── Legal/',
      '├── Projects/',
      '└── Templates/',
      '```',
      '',
      '## Best Practices',
      '',
      '1. **Consistent Naming**: Use date prefixes (YYYY-MM-DD)',
      '2. **Regular Backups**: Cloud sync important documents',
      '3. **Archive Old Files**: Move completed projects to Archives',
      '4. **Use Templates**: Create reusable document templates',
      '5. **Tag Metadata**: Add keywords to document properties',
      '',
      '## Security Recommendations',
      '',
      '- 🔒 Encrypt sensitive documents (financial, legal, medical)',
      '- 📝 Maintain separate folder for confidential files',
      '- 🔄 Enable version history for critical documents',
      '- ☁️ Use cloud backup with encryption',
      '',
      '---',
      `*AI-generated insights • ${now.toLocaleTimeString()}*`,
    ].join('\n')
  }
  
  // Report subfolder (inside Documents)
  if (folderNameLower === 'report' || folderNameLower === 'reports') {
    return [
      '# 📊 Reports',
      '',
      `**Path:** ${folderPath}`,
      '**Purpose:** Business reports, analytics, and data summaries',
      `**Last Updated:** ${now.toLocaleDateString()}`,
      '',
      '## Overview',
      '',
      'Dedicated folder for reports, analytics, and data-driven documents. Contains business intelligence, performance metrics, financial reports, and analysis documents.',
      '',
      '## Report Categories',
      '',
      '- **Financial**: Revenue, expenses, budgets, forecasts',
      '- **Performance**: KPIs, metrics, dashboards',
      '- **Analytics**: Data analysis, trends, insights',
      '- **Status**: Project updates, progress reports',
      '- **Compliance**: Regulatory and audit reports',
      '',
      '## AI Insights',
      '',
      '- 📈 **Data Quality:** Reports contain valuable business insights',
      '- 🎯 **Timeliness:** Keep reports organized by date/quarter',
      '- 📊 **Format Consistency:** Standardize report templates',
      '- 🔄 **Update Frequency:** Track which reports need regular updates',
      '',
      '## Organization Best Practices',
      '',
      '```',
      'Reports/',
      '├── 2024/',
      '│   ├── Q1/',
      '│   ├── Q2/',
      '│   ├── Q3/',
      '│   └── Q4/',
      '├── 2025/',
      '├── Annual/',
      '├── Monthly/',
      '└── Templates/',
      '```',
      '',
      '## Naming Convention',
      '',
      '- **Quarterly**: Q1-2025_Financial_Report.xlsx',
      '- **Monthly**: 2025-11_Sales_Analytics.pdf',
      '- **Annual**: Annual_Report_2024.docx',
      '- **Ad-hoc**: YYYY-MM-DD_Report_Topic.pdf',
      '',
      '## Recommendations',
      '',
      '1. ✅ Archive reports older than 2 years',
      '2. ✅ Create summary dashboard for quick insights',
      '3. ✅ Use consistent templates for each report type',
      '4. ✅ Add executive summaries to all major reports',
      '5. ✅ Implement version control for draft reports',
      '',
      '## Automation Opportunities',
      '',
      '- 🤖 Set up automatic report generation for recurring reports',
      '- 📧 Schedule email distribution for key stakeholders',
      '- 📊 Create live dashboards instead of static reports',
      '- 🔄 Sync with business intelligence tools',
      '',
      '---',
      `*AI-generated insights • ${now.toLocaleTimeString()}*`,
    ].join('\n')
  }
  
  return null // No specific note for this folder
}
